[package]
name = "entertainarr-transcode"
version = "0.1.0"
edition = "2024"

[dependencies]
any-storage = { workspace = true }
regex = { version = "1.11", default-features = false, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { version = "2.0" }
tokio = { workspace = true, features = ["process"] }
tokio-stream = { version = "0.1.17", default-features = false, features = ["io-util"] }
tokio-util = { version = "0.7", features = ["io"] }

[dev-dependencies]
any-storage = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
