[package]
name = "entertainarr-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
async-fs = "2.1"
futures-lite = "2.6"
pcloud = { version = "2.0" }
serde = { version = "1.0", features = ["derive"] }
