[package]
name = "entertainarr-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"
mime_guess = "2.0"
pcloud = { version = "3.1" }
reqwest = { version = "0.12", features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.44", features = ["fs"] }
tokio-util = { version = "0.7", features = ["io"] }
