[package]
name = "entertainarr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0" }
axum = { version = "0.8", features = ["macros"] }
base64ct = { version = "1.8", features = ["alloc"] }
bon = "3.8"
chrono = { version = "0.4", default-features = false, features = ["now"] }
jsonwebtoken = { version = "9.3", default-features = false }
nutype = "0.6"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
thiserror = { version = "2.0" }
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

[dev-dependencies]
mockall = "0.13"
tower = "0.5"
