[workspace]
resolver = "3"
members = [
    "packages/api",
    "packages/database",
    "packages/server",
    "packages/transcode",
    "packages/web",
]

[workspace.dependencies]
any-storage = { version = "0.3" }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
entertainarr-api = { path = "packages/api", version = "0.1" }
entertainarr-database = { path = "packages/database", version = "0.1" }
entertainarr-transcode = { path = "packages/transcode", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
tmdb-api = { version = "=1.0.0-alpha.2", default-features = false }
tokio = { version = "1.46", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1" }
