[workspace]
resolver = "3"
members = [
    "packages/api",
    "packages/database",
    "packages/server",
    "packages/storage",
    "packages/web",
]

[workspace.dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde"] }
entertainarr-api = { path = "packages/api", version = "0.1" }
entertainarr-database = { path = "packages/database", version = "0.1" }
entertainarr-storage = { path = "packages/storage", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
tmdb-api = { version = "0.9", default-features = false }
tokio = { version = "1.44", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1" }
