[package]
name = "entertainarr-web"
version = "0.1.0"
edition = "2024"

[dependencies]
entertainarr-api = { workspace = true }
gloo-net = { version = "0.6", features = ["http"] }
serde = { version = "1.0", features = ["derive"] }
web-sys = { version = "0.3" }
# this is the development version of Yew
yew = { version = "0.21", features = ["csr"] }
yew-hooks = { version = "0.3" }
yew-router = { version = "0.18" }
