[package]
name = "entertainarr-api"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", default-features = false, features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
tmdb-api = { workspace = true }
