[package]
name = "entertainarr-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["cookie", "typed-header"] }
chrono = { version = "0.4.40", default-features = false, features = ["serde"] }
config = { version = "0.15", default-features = false, features = ["toml"] }
constcat = "0.6.0"
entertainarr-api = { workspace = true }
entertainarr-storage = { workspace = true }
regex = { version = "1.11" }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "chrono",
    "runtime-tokio",
    "sqlite",
    "time",
] }
tmdb-api = { workspace = true, features = ["commands"] }
tokio = { version = "1.44", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.14", features = ["io"] }
toml = { version = "0.8" }
tower-http = { version = "0.6", features = ["trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
