[package]
name = "entertainarr-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.10", features = ["cookie", "typed-header"] }
chrono = { workspace = true, default-features = false, features = ["serde"] }
config = { version = "0.15", default-features = false, features = ["toml"] }
entertainarr-api = { workspace = true }
entertainarr-database = { workspace = true }
include_dir = { version = "0.7" }
mime_guess = "2.0"
regex = { version = "1.11" }
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0.12"
tmdb-api = { workspace = true, features = ["commands"] }
tokio = { workspace = true }
tokio-util = { version = "0.7.14", features = ["io"] }
toml = { version = "0.8" }
tower-http = { version = "0.6", features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
mockito = { version = "1.7" }
test-case = "3.3.1"
