[service.database]
url = "/etc/entertainarr/entertainarr.db"

[service.storage.tvshow.store]
type = "local"
root = "/data/tvshow"

[service.tmdb]
token = "...."

# [service.worker]
# tick_interval = 3600

[[dataset.users]]
id = 1
name = "Jeremie"
